name: Go
on: 
  pull_request:
    branches: 
      - master
  push:
    branches: 
      - master
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Read Go versions
        run: echo "##[set-output name=go_version;]$(cat .github/versions/go)"
        id: go_versions

      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ steps.go_versions.outputs.go_version }}
          id: go

      - name: Build and test
        run: cd .travis && make
